server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sgdev_manager
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
#      schema-locations: classpath*:data/schema.sql
#      data-locations: classpath*:data/

logging.level:
  org.hibernate.SQL: debug

