server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  application:
    name: manager-server
  datasource:
    url: ${DB_URL}
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath*:data/broadcast-schema.sql, classpath*:data/publisher-schema.sql, classpath*:data/room-schema.sql

logging.level:
  org.hibernate.SQL: debug

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS}
  client:
    service-url:
      defaultZone: ${EUREKA_ADDRESS}